spring:
  application:
    name: ecommerce
    version: v0.1.0-alpha
  profiles:
    active: "test"
  jpa:
    open-in-view: false

security:
  password:
    encoder:
      secret: "DQvnCBpT2X1o797Mqez9xNtD9kPPxulf"
      iterations: 185000
      salt-length: 16
  jwt:
    token:
      secret-key: "fjilmpmaKTk4ZpLrsP2ecqFfZpqzP1bY"
      expire-length: 3600000

spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true

server:
  servlet:
    context-path: /api

cors:
  originPatterns: ${CORS_ORIGINS:http://localhost:4200}